use regex::Regex;
use lazy_static::lazy_static;
use serde::{Deserialize, Serialize};

/// 风险严重程度
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Severity {
    Low,
    Medium,
    High,
    Critical,
}

/// 风险类别
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Category {
    Destructive,      // 破坏性操作
    RemoteExec,       // 远程执行
    CmdInjection,     // 命令注入
    Network,          // 网络外传
    Privilege,        // 权限提升
    Secrets,          // 敏感泄露
    Persistence,      // 持久化
    SensitiveFileAccess,  // 敏感文件访问
}

/// 置信度等级
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Confidence {
    High,    // 高置信度，误报可能性低
    Medium,  // 中等置信度
    Low,     // 低置信度，可能误报
}

/// 危险模式规则
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct PatternRule {
    pub id: &'static str,
    pub name: &'static str,
    pub pattern: Regex,
    pub severity: Severity,
    pub category: Category,
    pub weight: i32,
    pub description: &'static str,
    pub hard_trigger: bool,
    pub confidence: Confidence,           // 新增
    pub remediation: &'static str,        // 新增：修复建议
    pub cwe_id: Option<&'static str>,     // 新增：CWE 编号
}

impl PatternRule {
    #[allow(clippy::too_many_arguments)]
    fn new(
        id: &'static str,
        name: &'static str,
        pattern: &'static str,
        severity: Severity,
        category: Category,
        weight: i32,
        description: &'static str,
        hard_trigger: bool,
        confidence: Confidence,           // 新增
        remediation: &'static str,        // 新增
        cwe_id: Option<&'static str>,     // 新增
    ) -> Self {
        Self {
            id,
            name,
            pattern: Regex::new(pattern).expect("Invalid regex pattern"),
            severity,
            category,
            weight,
            description,
            hard_trigger,
            confidence,      // 新增
            remediation,     // 新增
            cwe_id,          // 新增
        }
    }
}

lazy_static! {
    /// 所有危险模式规则库
    pub static ref PATTERN_RULES: Vec<PatternRule> = vec![
        // A. 破坏性操作
        PatternRule::new(
            "RM_RF_ROOT",
            "删除根目录",
            r"rm\s+(-[a-zA-Z]*)*\s*-r[a-zA-Z]*\s+(-[a-zA-Z]*\s+)*/($|\s|;|\|)",
            Severity::Critical,
            Category::Destructive,
            100,
            "rm -rf / 删除根目录",
            true,
            Confidence::High,
            "检查命令参数，避免操作根目录或使用通配符",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "RM_RF_HOME",
            "删除用户目录",
            r"rm\s+(-[a-zA-Z]*)*\s*-r[a-zA-Z]*\s+(-[a-zA-Z]*\s+)*(~|\$HOME)",
            Severity::Critical,
            Category::Destructive,
            90,
            "rm -rf ~ 删除用户目录",
            true,
            Confidence::High,
            "检查命令参数，避免操作用户主目录",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "DD_WIPE",
            "磁盘擦除",
            r"dd\s+.*of=/dev/(sd[a-z]|nvme|hd[a-z]|vd[a-z])",
            Severity::Critical,
            Category::Destructive,
            100,
            "dd 写入磁盘设备",
            true,
            Confidence::High,
            "检查命令参数，避免写入系统磁盘设备",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "MKFS_FORMAT",
            "格式化磁盘",
            r"mkfs(\.[a-z0-9]+)?\s+/dev/",
            Severity::Critical,
            Category::Destructive,
            100,
            "mkfs 格式化命令",
            true,
            Confidence::High,
            "检查命令参数，避免格式化系统磁盘",
            Some("CWE-78"),
        ),

        // B. 远程执行
        PatternRule::new(
            "CURL_PIPE_SH",
            "Curl管道执行",
            r"curl\s+[^|]*\|\s*(ba)?sh",
            Severity::Critical,
            Category::RemoteExec,
            90,
            "curl | sh 远程执行",
            true,
            Confidence::High,
            "避免直接执行远程脚本，应先下载后检查",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "WGET_PIPE_SH",
            "Wget管道执行",
            r"wget\s+[^|]*\|\s*(ba)?sh",
            Severity::Critical,
            Category::RemoteExec,
            90,
            "wget | sh 远程执行",
            true,
            Confidence::High,
            "避免直接执行远程脚本，应先下载后检查",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "BASE64_EXEC",
            "Base64解码执行",
            r"base64\s+(-d|--decode)[^|]*\|\s*(ba)?sh",
            Severity::Critical,
            Category::RemoteExec,
            85,
            "base64 解码后执行",
            true,
            Confidence::High,
            "避免执行Base64编码的命令，可能隐藏恶意代码",
            Some("CWE-506"),
        ),
        PatternRule::new(
            "REVERSE_SHELL",
            "反弹Shell",
            r"(socket\.socket|s\.connect|os\.dup2|subprocess\.call.*bin/(ba)?sh)",
            Severity::Critical,
            Category::RemoteExec,
            95,
            "反弹Shell后门",
            true,
            Confidence::High,
            "检查网络连接和进程调用，避免反弹Shell后门",
            Some("CWE-506"),
        ),

        // C. 命令注入
        PatternRule::new(
            "PY_EVAL",
            "Python eval",
            r"\beval\s*\(",
            Severity::High,
            Category::CmdInjection,
            70,
            "eval() 动态执行",
            false,
            Confidence::Medium,
            "避免使用eval()动态执行代码，使用安全的替代方法",
            Some("CWE-94"),
        ),
        PatternRule::new(
            "PY_EXEC",
            "Python exec",
            r"\bexec\s*\(",
            Severity::High,
            Category::CmdInjection,
            70,
            "exec() 动态执行",
            false,
            Confidence::Medium,
            "避免使用exec()动态执行代码，使用安全的替代方法",
            Some("CWE-94"),
        ),
        PatternRule::new(
            "OS_SYSTEM",
            "os.system",
            r"os\.system\s*\(",
            Severity::High,
            Category::CmdInjection,
            65,
            "os.system() Shell执行",
            false,
            Confidence::Medium,
            "避免使用os.system()，改用subprocess.run()并设置shell=False",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "SUBPROCESS_SHELL",
            "subprocess shell=True",
            r"subprocess\.(run|call|Popen)\s*\([^)]*shell\s*=\s*True",
            Severity::High,
            Category::CmdInjection,
            65,
            "subprocess shell=True",
            false,
            Confidence::High,
            "避免设置shell=True，使用列表参数传递命令",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "SUBPROCESS_CALL",
            "subprocess 调用",
            r"subprocess\.(run|call|Popen)\s*\(",
            Severity::Medium,
            Category::CmdInjection,
            25,
            "subprocess 进程调用",
            false,
            Confidence::Low,
            "确保命令参数经过验证，避免注入风险",
            Some("CWE-78"),
        ),

        // D. 网络外传
        PatternRule::new(
            "CURL_POST",
            "Curl POST",
            r"curl\s+[^;|]*-X\s*POST",
            Severity::Medium,
            Category::Network,
            40,
            "curl POST 请求",
            false,
            Confidence::Medium,
            "确认网络请求目标，避免泄露敏感数据",
            Some("CWE-319"),
        ),
        PatternRule::new(
            "NETCAT",
            "Netcat连接",
            r"\bnc\s+(-[a-z]*\s+)*[a-zA-Z0-9.-]+\s+\d+",
            Severity::High,
            Category::Network,
            60,
            "netcat 网络连接",
            false,
            Confidence::Medium,
            "检查netcat使用场景，避免未授权的网络连接",
            Some("CWE-319"),
        ),
        PatternRule::new(
            "PY_URLLIB",
            "Python urllib",
            r"urllib\.request\.urlopen\s*\(",
            Severity::Medium,
            Category::Network,
            35,
            "urllib 网络请求",
            false,
            Confidence::Low,
            "确认请求目标URL的安全性，使用HTTPS协议",
            None,
        ),
        PatternRule::new(
            "HTTP_REQUEST",
            "HTTP 请求库",
            r"requests\.(get|post|put|delete|patch)\s*\(",
            Severity::Low,
            Category::Network,
            15,
            "Python requests HTTP 请求",
            false,
            Confidence::Low,
            "确认请求目标URL的安全性，使用HTTPS协议",
            None,
        ),

        // E. 权限提升
        PatternRule::new(
            "SUDO",
            "sudo提权",
            r"\bsudo\s+",
            Severity::High,
            Category::Privilege,
            60,
            "sudo 权限提升",
            false,
            Confidence::Low,
            "审查sudo使用场景，确保符合最小权限原则",
            Some("CWE-250"),
        ),
        PatternRule::new(
            "CHMOD_777",
            "chmod 777",
            r"chmod\s+(-[a-zA-Z]*\s+)*7[0-7]{2}",
            Severity::High,
            Category::Privilege,
            55,
            "chmod 777 开放权限",
            false,
            Confidence::High,
            "避免设置777权限，使用最小权限原则",
            Some("CWE-732"),
        ),
        PatternRule::new(
            "SUDOERS",
            "sudoers修改",
            r"(/etc/sudoers|visudo|NOPASSWD)",
            Severity::Critical,
            Category::Privilege,
            95,
            "sudoers 文件修改",
            true,
            Confidence::High,
            "检查sudoers修改，避免不当的权限配置",
            Some("CWE-250"),
        ),

        // F. 持久化
        PatternRule::new(
            "CRONTAB",
            "Crontab持久化",
            r"(crontab\s+-|/etc/cron)",
            Severity::High,
            Category::Persistence,
            65,
            "crontab 持久化",
            false,
            Confidence::Medium,
            "检查定时任务内容，避免恶意持久化机制",
            Some("CWE-506"),
        ),
        PatternRule::new(
            "SSH_KEYS",
            "SSH密钥注入",
            r"(>>|>)\s*~?/?(\.ssh/authorized_keys|\.ssh/id_)",
            Severity::Critical,
            Category::Persistence,
            90,
            "SSH 密钥写入",
            true,
            Confidence::High,
            "检查SSH密钥写入操作，避免未授权访问",
            Some("CWE-506"),
        ),

        // G. 敏感泄露
        PatternRule::new(
            "PRIVATE_KEY",
            "私钥硬编码",
            r"-----BEGIN\s+(RSA|OPENSSH|EC|DSA)?\s*PRIVATE KEY-----",
            Severity::High,
            Category::Secrets,
            70,
            "硬编码私钥",
            false,
            Confidence::High,
            "使用环境变量或密钥管理服务，不要硬编码私钥",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "API_KEY",
            "API Key",
            r#"(api[_-]?key|apikey|api_secret)\s*[=:]\s*["'][a-zA-Z0-9_-]{16,}["']"#,
            Severity::High,
            Category::Secrets,
            60,
            "硬编码 API Key",
            false,
            Confidence::High,
            "使用环境变量或密钥管理服务，不要硬编码API密钥",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "PASSWORD",
            "密码硬编码",
            r#"(password|passwd|pwd)\s*[=:]\s*["'][^"']{4,}["']"#,
            Severity::High,
            Category::Secrets,
            55,
            "硬编码密码",
            false,
            Confidence::Medium,
            "使用环境变量或配置文件，不要硬编码密码",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "AWS_KEY",
            "AWS密钥",
            r"(AKIA|ASIA)[A-Z0-9]{16}",
            Severity::Critical,
            Category::Secrets,
            80,
            "AWS Access Key",
            false,
            Confidence::High,
            "使用AWS密钥管理服务或环境变量，不要硬编码AWS密钥",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "GITHUB_TOKEN",
            "GitHub Token",
            r"ghp_[a-zA-Z0-9]{36}",
            Severity::Critical,
            Category::Secrets,
            80,
            "GitHub Token",
            false,
            Confidence::High,
            "使用GitHub Secrets或环境变量，不要硬编码Token",
            Some("CWE-798"),
        ),

        // H. 敏感文件访问
        PatternRule::new(
            "READ_SSH_PRIVATE_KEY",
            "读取SSH私钥",
            r"(cat|less|head|tail|vim|nano|open)\s+.*\.ssh/(id_rsa|id_dsa|id_ecdsa|id_ed25519)($|\s)",
            Severity::High,
            Category::SensitiveFileAccess,
            70,
            "读取SSH私钥文件",
            false,
            Confidence::High,
            "避免直接读取私钥文件，使用ssh-agent管理密钥",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_AWS_CREDENTIALS",
            "读取AWS凭证",
            r"(cat|less|head|tail|vim|nano|open)\s+.*\.aws/credentials",
            Severity::High,
            Category::SensitiveFileAccess,
            70,
            "读取AWS凭证文件",
            false,
            Confidence::High,
            "使用AWS IAM角色或环境变量，避免读取凭证文件",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_ENV_FILE",
            "读取.env文件",
            r"(cat|less|head|tail|vim|nano|open)\s+.*\.env($|\s)",
            Severity::Medium,
            Category::SensitiveFileAccess,
            50,
            "读取环境变量配置文件",
            false,
            Confidence::Medium,
            "确保.env文件不包含敏感信息，或使用密钥管理服务",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_PASSWD",
            "读取passwd文件",
            r"(cat|less|head|tail)\s+/etc/passwd",
            Severity::Medium,
            Category::SensitiveFileAccess,
            45,
            "读取系统用户信息",
            false,
            Confidence::High,
            "确认是否需要读取用户信息，避免信息泄露",
            Some("CWE-200"),
        ),
        PatternRule::new(
            "READ_SHADOW",
            "读取shadow文件",
            r"(cat|less|head|tail)\s+/etc/shadow",
            Severity::Critical,
            Category::SensitiveFileAccess,
            85,
            "读取系统密码哈希文件",
            true,
            Confidence::High,
            "绝不应读取shadow文件，这是严重的安全风险",
            Some("CWE-522"),
        ),
        PatternRule::new(
            "READ_GIT_CREDENTIALS",
            "读取Git凭证",
            r"(cat|less|head|tail|vim|nano|open)\s+.*\.git-credentials",
            Severity::High,
            Category::SensitiveFileAccess,
            65,
            "读取Git凭证存储文件",
            false,
            Confidence::High,
            "使用SSH密钥或凭证管理器，避免明文存储Git凭证",
            Some("CWE-522"),
        ),

        // I. Node.js 命令注入
        PatternRule::new(
            "NODE_CHILD_EXEC",
            "Node.js child_process.exec",
            r"child_process\.exec\s*\(",
            Severity::High,
            Category::CmdInjection,
            70,
            "Node.js child_process.exec 执行",
            false,
            Confidence::High,
            "避免使用exec()，改用execFile()或spawn()并验证参数",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "NODE_VM_RUN",
            "Node.js vm.runInNewContext",
            r"vm\.runInNewContext\s*\(",
            Severity::High,
            Category::CmdInjection,
            65,
            "Node.js 动态代码执行",
            false,
            Confidence::High,
            "避免动态执行未验证的代码，使用安全的替代方案",
            Some("CWE-94"),
        ),
        PatternRule::new(
            "NODE_EVAL",
            "Node.js eval",
            r"\beval\s*\(",
            Severity::High,
            Category::CmdInjection,
            70,
            "JavaScript eval() 动态执行",
            false,
            Confidence::Medium,  // eval 在 JS 中有合法用途
            "避免使用eval()，使用JSON.parse()或Function构造函数的安全替代",
            Some("CWE-94"),
        ),

        // J. 敏感数据泄露增强
        PatternRule::new(
            "JWT_TOKEN",
            "JWT Token 硬编码",
            r"eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}",
            Severity::High,
            Category::Secrets,
            75,
            "硬编码的 JWT Token",
            false,
            Confidence::High,
            "不要硬编码JWT Token，使用安全的存储方式",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "DB_CONNECTION_STRING",
            "数据库连接串",
            r#"(mongodb|mysql|postgresql|postgres)://[^\s"']{10,}"#,
            Severity::High,
            Category::Secrets,
            70,
            "硬编码的数据库连接字符串",
            false,
            Confidence::High,
            "使用环境变量或配置文件管理数据库连接串，不要硬编码",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "SLACK_WEBHOOK",
            "Slack Webhook URL",
            r"https://hooks\.slack\.com/services/[A-Z0-9/]{30,}",
            Severity::Medium,
            Category::Secrets,
            50,
            "硬编码的 Slack Webhook URL",
            false,
            Confidence::High,
            "使用环境变量存储 Webhook URL",
            Some("CWE-798"),
        ),
        PatternRule::new(
            "GENERIC_SECRET",
            "通用密钥模式",
            r#"(secret|token|key)\s*[=:]\s*[\"'][a-zA-Z0-9_-]{16,}[\"']"#,
            Severity::Medium,
            Category::Secrets,
            45,
            "可能的硬编码密钥",
            false,
            Confidence::Low,  // 误报可能性较高
            "检查是否为敏感密钥，使用密钥管理服务",
            Some("CWE-798"),
        ),

        // K. 网络行为增强
        PatternRule::new(
            "WEBSOCKET_CONNECT",
            "WebSocket 连接",
            r"(new\s+WebSocket|ws://|wss://)",
            Severity::Low,
            Category::Network,
            25,
            "WebSocket 连接",
            false,
            Confidence::Low,
            "确认 WebSocket 连接的安全性，使用 wss:// 加密连接",
            None,
        ),
        PatternRule::new(
            "FTP_PROTOCOL",
            "FTP 协议使用",
            r"ftp://",
            Severity::Medium,
            Category::Network,
            40,
            "使用不安全的 FTP 协议",
            false,
            Confidence::High,
            "使用 SFTP 或 FTPS 替代明文 FTP",
            Some("CWE-319"),
        ),

        // ========== L. JavaScript/TypeScript 特有规则 (10条) ==========

        PatternRule::new(
            "JS_DANGEROUSLY_SET_INNER_HTML",
            "React dangerouslySetInnerHTML",
            r"dangerouslySetInnerHTML\s*=\s*\{\{",
            Severity::High,
            Category::CmdInjection,
            60,
            "React dangerouslySetInnerHTML 使用（XSS 风险）",
            false,
            Confidence::High,
            "避免使用 dangerouslySetInnerHTML，或使用 DOMPurify 清理 HTML",
            Some("CWE-79"),
        ),
        PatternRule::new(
            "JS_INNER_HTML",
            "JavaScript innerHTML",
            r"\.innerHTML\s*=",
            Severity::Medium,
            Category::CmdInjection,
            50,
            "JavaScript innerHTML 赋值（XSS 风险）",
            false,
            Confidence::Medium,
            "使用 textContent 或 createElement 替代 innerHTML",
            Some("CWE-79"),
        ),
        PatternRule::new(
            "JS_DOCUMENT_WRITE",
            "document.write 调用",
            r"document\.write\s*\(",
            Severity::High,
            Category::CmdInjection,
            55,
            "document.write() 调用（XSS 风险）",
            false,
            Confidence::High,
            "避免使用 document.write()，使用 DOM 方法替代",
            Some("CWE-79"),
        ),
        PatternRule::new(
            "JS_SET_TIMEOUT_STRING",
            "setTimeout 字符串参数",
            r#"setTimeout\s*\(\s*['"]"#,
            Severity::Medium,
            Category::CmdInjection,
            45,
            "setTimeout() 使用字符串参数(代码注入风险)",
            false,
            Confidence::Medium,
            "使用函数参数替代字符串参数",
            Some("CWE-94"),
        ),
        PatternRule::new(
            "JS_SET_INTERVAL_STRING",
            "setInterval 字符串参数",
            r#"setInterval\s*\(\s*['"]"#,
            Severity::Medium,
            Category::CmdInjection,
            45,
            "setInterval() 使用字符串参数(代码注入风险)",
            false,
            Confidence::Medium,
            "使用函数参数替代字符串参数",
            Some("CWE-94"),
        ),
        PatternRule::new(
            "JS_POST_MESSAGE",
            "postMessage 不安全调用",
            r"\.postMessage\s*\(",
            Severity::Low,
            Category::Network,
            30,
            "postMessage() 调用（需验证 origin）",
            false,
            Confidence::Low,
            "确保在接收消息时验证 origin 参数",
            Some("CWE-346"),
        ),
        PatternRule::new(
            "JS_LOCAL_STORAGE_SENSITIVE",
            "localStorage 存储敏感信息",
            r#"localStorage\.(setItem|setItem)\s*\(\s*['"]*(token|password|secret|key)"#,
            Severity::Medium,
            Category::Secrets,
            50,
            "localStorage 存储敏感信息（明文存储）",
            false,
            Confidence::Medium,
            "敏感信息应使用 sessionStorage 或 httpOnly cookie",
            Some("CWE-922"),
        ),
        PatternRule::new(
            "JS_LOCATION_ASSIGN",
            "location.assign 未验证URL",
            r"location\.(assign|replace|href)\s*=",
            Severity::Medium,
            Category::Network,
            40,
            "location.assign/replace 调用（开放重定向风险）",
            false,
            Confidence::Medium,
            "验证重定向 URL，避免开放重定向漏洞",
            Some("CWE-601"),
        ),
        PatternRule::new(
            "JS_FUNCTION_CONSTRUCTOR",
            "Function 构造函数",
            r"new\s+Function\s*\(",
            Severity::High,
            Category::CmdInjection,
            65,
            "Function() 构造函数（代码生成风险）",
            false,
            Confidence::High,
            "避免使用 Function 构造函数动态生成代码",
            Some("CWE-94"),
        ),
        PatternRule::new(
            "JS_DYNAMIC_IMPORT",
            "动态 import() 未验证",
            r#"import\s*\(\s*[^)]*['"][^'"]*['"]"#,
            Severity::Low,
            Category::Network,
            35,
            "动态 import() 加载模块",
            false,
            Confidence::Low,
            "验证动态导入的模块路径，避免代码注入",
            Some("CWE-94"),
        ),

        // ========== M. Rust 特有规则 (5条) ==========

        PatternRule::new(
            "RUST_UNSAFE_BLOCK",
            "Rust unsafe 块",
            r"\bunsafe\b\s*\{",
            Severity::Medium,
            Category::CmdInjection,
            55,
            "Rust unsafe 块（绕过安全检查）",
            false,
            Confidence::High,
            "审查 unsafe 代码，确保内存安全，考虑使用安全的抽象",
            Some("CWE-119"),
        ),
        PatternRule::new(
            "RUST_RAW_POINTER",
            "Rust 原始指针",
            r"\*const\s+\w+|\*mut\s+\w+",
            Severity::High,
            Category::CmdInjection,
            60,
            "Rust 原始指针操作（内存安全风险）",
            false,
            Confidence::High,
            "优先使用引用和智能指针（Box, Rc, Arc）",
            Some("CWE-119"),
        ),
        PatternRule::new(
            "RUST_TRANSMUTE",
            "Rust transmute 类型转换",
            r"(std::mem::|mem::)?transmute\s*\(",
            Severity::High,
            Category::CmdInjection,
            70,
            "Rust transmute 类型转换（未定义行为风险）",
            false,
            Confidence::High,
            "避免使用 transmute，使用安全的类型转换方法",
            Some("CWE-758"),
        ),
        PatternRule::new(
            "RUST_EXTERN_C",
            "Rust extern \"C\" FFI",
            r#"extern\s+['"]C['"]"#,
            Severity::Medium,
            Category::CmdInjection,
            50,
            "Rust FFI 外部函数调用（潜在不安全）",
            false,
            Confidence::Medium,
            "确保 FFI 调用的外部库可信且安全",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "RUST_MEM_FORGET",
            "Rust std::mem::forget",
            r"std::mem::forget\s*\(",
            Severity::Low,
            Category::Destructive,
            30,
            "Rust std::mem::forget 调用（内存泄漏风险）",
            false,
            Confidence::Medium,
            "审查内存管理逻辑，避免内存泄漏",
            Some("CWE-404"),
        ),

        // ========== N. Tauri 特有规则 (3条) ==========

        PatternRule::new(
            "TAURI_INVOKE",
            "Tauri invoke() 调用",
            r#"invoke\s*\(\s*['"]"#,
            Severity::Low,
            Category::RemoteExec,
            25,
            "Tauri invoke() 调用后端命令",
            false,
            Confidence::Low,
            "确保只调用已注册的 Tauri 命令，验证命令名称",
            None,
        ),
        PatternRule::new(
            "TAURI_COMMAND_NEW",
            "Tauri Command::new() 执行",
            r"Command::new\s*\(",
            Severity::High,
            Category::CmdInjection,
            65,
            "Tauri Command 执行系统命令",
            false,
            Confidence::High,
            "验证命令参数，避免命令注入",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "TAURI_FS_API",
            "Tauri 文件系统 API",
            r"(read|write|remove|rename)File|readDir|createDir",
            Severity::Medium,
            Category::SensitiveFileAccess,
            45,
            "Tauri 文件系统 API 调用",
            false,
            Confidence::Low,
            "确保文件路径验证，避免路径遍历攻击",
            Some("CWE-22"),
        ),

        // ========== O. Go 语言特有规则 (4条) ==========

        PatternRule::new(
            "GO_UNSAFE_PACKAGE",
            "Go unsafe 包使用",
            r#"import\s+"unsafe"|unsafe\."#,
            Severity::Medium,
            Category::CmdInjection,
            55,
            "Go unsafe 包使用（绕过类型安全）",
            false,
            Confidence::High,
            "审查 unsafe 代码，确保内存安全，考虑使用安全的替代方案",
            Some("CWE-119"),
        ),
        PatternRule::new(
            "GO_CGO_USAGE",
            "Go CGo 外部函数调用",
            r#"import\s+"C"|//\s*#cgo"#,
            Severity::Medium,
            Category::CmdInjection,
            50,
            "Go CGo 调用 C 代码（潜在不安全）",
            false,
            Confidence::High,
            "确保 C 代码可信且安全，验证内存管理",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "GO_GOROUTINE_LEAK",
            "Go goroutine 泄漏风险",
            r"go\s+func\s*\(|go\s+\w+\(",
            Severity::Low,
            Category::Destructive,
            30,
            "Go goroutine 调用（可能泄漏）",
            false,
            Confidence::Low,
            "确保 goroutine 正确退出，使用 context 管理生命周期",
            Some("CWE-404"),
        ),
        PatternRule::new(
            "GO_RACE_CONDITION",
            "Go 数据竞争检测",
            r"go\s+func.*\{.*[^&]([\w\.]+)\s*=",
            Severity::Medium,
            Category::CmdInjection,
            45,
            "Go 并发访问共享变量（数据竞争风险）",
            false,
            Confidence::Low,
            "使用 sync.Mutex 或 channel 保护共享数据，运行 go build -race 检测",
            Some("CWE-362"),
        ),

        // ========== P. Python 语言特有规则 (4条) ==========

        PatternRule::new(
            "PYTHON_PICKLE_LOAD",
            "Python pickle 不安全反序列化",
            r"pickle\.load(s)?\s*\(",
            Severity::Critical,
            Category::CmdInjection,
            85,
            "Python pickle.load 不安全反序列化（远程代码执行）",
            true,
            Confidence::High,
            "避免反序列化不可信数据，使用 JSON 或其他安全格式",
            Some("CWE-502"),
        ),
        PatternRule::new(
            "PYTHON_YAML_LOAD",
            "Python yaml.load 不安全加载",
            r"yaml\.load\s*\([^,)]*\)|yaml\.unsafe_load",
            Severity::High,
            Category::CmdInjection,
            75,
            "Python yaml.load 不安全加载（代码执行风险）",
            false,
            Confidence::High,
            "使用 yaml.safe_load() 替代 yaml.load()",
            Some("CWE-94"),
        ),
        PatternRule::new(
            "PYTHON_CODE_COMPILE",
            "Python compile 动态编译",
            r"\bcompile\s*\(",
            Severity::High,
            Category::CmdInjection,
            70,
            "Python compile() 动态编译代码",
            false,
            Confidence::Medium,
            "避免编译未验证的代码，使用安全的替代方法",
            Some("CWE-94"),
        ),
        PatternRule::new(
            "PYTHON_INPUT_RAW",
            "Python input 未验证输入",
            r"\binput\s*\(",
            Severity::Low,
            Category::CmdInjection,
            25,
            "Python input() 接收用户输入（需验证）",
            false,
            Confidence::Low,
            "验证和清理用户输入，避免注入攻击",
            Some("CWE-20"),
        ),

        // ========== Q. Shell 脚本特有规则 (4条) ==========

        PatternRule::new(
            "SHELL_WORD_SPLITTING",
            "Shell 单词分割漏洞",
            r#"(rm|mv|cp|cat)\s+\$\w+|\$\{\w+\}"#,
            Severity::Medium,
            Category::CmdInjection,
            50,
            "Shell 变量未引号包裹（单词分割风险）",
            false,
            Confidence::Medium,
            r#"使用双引号包裹变量: "$var" 而不是 $var"#,
            Some("CWE-78"),
        ),
        PatternRule::new(
            "SHELL_GLOB_EXPANSION",
            "Shell 通配符扩展风险",
            r"rm\s+.*\*|mv\s+.*\*",
            Severity::High,
            Category::Destructive,
            60,
            "Shell 通配符扩展（可能误删文件）",
            false,
            Confidence::Medium,
            "小心使用通配符，先测试匹配结果，使用 -- 分隔选项和参数",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "SHELL_COMMAND_SUBSTITUTION",
            "Shell 命令替换注入",
            r"\$\(.*\$\{?\w+\}?.*\)|`.*\$\{?\w+\}?.*`",
            Severity::High,
            Category::CmdInjection,
            65,
            "Shell 命令替换包含变量（注入风险）",
            false,
            Confidence::Medium,
            "验证变量内容，避免在命令替换中使用未验证的变量",
            Some("CWE-78"),
        ),
        PatternRule::new(
            "SHELL_SOURCE_UNTRUSTED",
            "Shell source 不可信文件",
            r"(source|\\.)\s+\$\{?\w+\}?|source\s+/tmp/",
            Severity::High,
            Category::RemoteExec,
            70,
            "Shell source 执行不可信文件",
            false,
            Confidence::High,
            "避免 source 用户可控的文件路径，验证文件来源",
            Some("CWE-94"),
        ),
    ];

    /// 仅获取硬触发规则
    pub static ref HARD_TRIGGER_RULES: Vec<&'static PatternRule> = {
        PATTERN_RULES.iter().filter(|r| r.hard_trigger).collect()
    };
}

pub struct SecurityRules;

impl SecurityRules {
    /// 获取所有模式规则
    pub fn get_all_patterns() -> &'static Vec<PatternRule> {
        &PATTERN_RULES
    }

    /// 获取所有硬触发规则
    #[allow(dead_code)]
    pub fn get_hard_triggers() -> Vec<&'static PatternRule> {
        PATTERN_RULES.iter().filter(|r| r.hard_trigger).collect()
    }
}
